# Generated by Django 4.0.3 on 2022-04-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='low_text',
            field=models.CharField(default='text', max_length=160),
        ),
    ]
